name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
            docker build . -t j00mz/viz-avocado:latest
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push j00mz/viz-avocado:latest
        
      
  

