name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build-and-push:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            git_hash: $(git rev-parse --short "$GITHUB_SHA")
      - name: Build and push Docker image
        run: |
            docker build . --file Dockerfile --tag j00mz/crawltricks:${git_hash}
            docker login -u ${username} -p ${password}
            docker push j00mz/crawltricks:${git_hash}
        
      
  

