# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build the Docker image 
      run: docker build . --file Dockerfile --tag avocado-file-toaster:$(date +%s) --build-arg ${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Push updated docker image to ECR
      uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: avocado-file-toaster
        region: eu-west-1
        tags: latest,${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy new lambda function from new docker image in ECR
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: avocado-file-toaster
        image_uri: 089164213324.dkr.ecr.eu-west-1.amazonaws.com/avocado-file-toaster:latest
        dry_run: true
